### Linear Regression

y = x*w + b

In [1]:
import torch

In [5]:
import numpy as np
np.random.seed(14)
x = np.random.randint(0,50,20)
x = x.reshape(10,2)
x = torch.from_numpy(x)
x = x*1.
x

tensor([[43., 24.],
        [12., 22.],
        [ 7., 38.],
        [42., 28.],
        [10., 16.],
        [40., 45.],
        [26., 25.],
        [23., 43.],
        [32.,  4.],
        [13., 10.]])

In [6]:
np.random.seed(4)
y = np.random.randint(0,50,10)
y = torch.from_numpy(y)
y = y*1.
y

tensor([46.,  5.,  1., 40., 23.,  8.,  9., 39., 45., 30.])

In [7]:
w = torch.rand(1,2, requires_grad=True)
b = torch.rand(1, requires_grad=True)
print(w)
print(b)

tensor([[0.0200, 0.2291]], requires_grad=True)
tensor([0.9293], requires_grad=True)


In [8]:
def model(x):
    return x @ w.t() + b

In [9]:
pred = model(x)

In [10]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [11]:
loss = mse(pred, y)
loss

tensor(590.4531, grad_fn=<DivBackward0>)

In [20]:
# Train for 1000 epochs
for i in range(1000):
    preds = model(x)
    loss = mse(preds, y)
    loss.backward(retain_graph=True)
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [21]:
# Calculate loss
preds = model(x)
loss = mse(preds, y)
print(loss)

tensor(351.7719, grad_fn=<DivBackward0>)


In [22]:
preds

tensor([[27.6757],
        [15.2912],
        [20.0597],
        [28.9610],
        [12.0585],
        [35.2624],
        [21.7533],
        [28.0964],
        [15.2850],
        [10.6897]], grad_fn=<AddBackward0>)

In [23]:
y

tensor([46.,  5.,  1., 40., 23.,  8.,  9., 39., 45., 30.])